name: GitHub Actions

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  build-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: jdx/mise-action@e79ddf65a11cec7b0e882bedced08d6e976efb2d # v3.6.2
        with:
          install: true
          cache: true

      - run: mise lint
      - run: mise build

      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: dist
          path: dist
          if-no-files-found: error
          retention-days: 1
          include-hidden-files: true

  test:
    name: test on Node.js v${{ matrix.node-version }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        node-version:
          - 20
          - 22
          - 24
    env:
      # Override Node.js version over mise.toml
      MISE_NODE_VERSION: ${{ matrix.node-version }}
    steps:

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: jdx/mise-action@e79ddf65a11cec7b0e882bedced08d6e976efb2d # v3.6.2
        with:
          install: true
          cache: true

      - run: mise test

  publish:
    needs:
      - build-lint
      - test
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      id-token: write # required to publish npm package
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: jdx/mise-action@e79ddf65a11cec7b0e882bedced08d6e976efb2d # v3.6.2
        with:
          install: true
          cache: true

      - uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8.0.0
        with:
          name: dist
          path: dist

      - run: npm publish
